# Generated by Django 4.0 on 2021-12-10 21:39

import django.db.models.deletion
import hashid_field.field
import sfdo_template_helpers.fields.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0106_project_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",  # noqa
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    sfdo_template_helpers.fields.string.StringField(
                        choices=[
                            ("Merged", "Merged"),
                            ("Approved", "Approved"),
                            ("Closed", "Closed"),
                            ("Test Org created", "Test Org Created"),
                            ("Test Org deleted", "Test Org Deleted"),
                            ("Dev Org created", "Dev Org Created"),
                            ("Dev Org deleted", "Dev Org Deleted"),
                            ("Submitted for testing", "Submitted For Testing"),
                            ("Changes retrieved", "Changes Retrieved"),
                            ("Changes requested", "Changes Requested"),
                            ("Tester accepted", "Tester Accepted"),
                            ("Tester assigned", "Tester Assigned"),
                            ("Tester unassigned", "Tester Unassigned"),
                            ("Developer accepted", "Dev Accepted"),
                            ("Developer assigned", "Dev Assigned"),
                            ("Developer unassigned", "Dev Unassigned"),
                            ("Created", "Created"),
                        ]
                    ),
                ),
                (
                    "link_title",
                    sfdo_template_helpers.fields.string.StringField(blank=True),
                ),
                ("link_url", models.URLField(blank=True)),
                (
                    "description",
                    sfdo_template_helpers.fields.string.StringField(blank=True),
                ),
                (
                    "collaborator_id",
                    sfdo_template_helpers.fields.string.StringField(blank=True),
                ),
                (
                    "scratch_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_activities",
                        to="api.scratchorg",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="api.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "task activity",
                "verbose_name_plural": "task activities",
                "ordering": ("-created_at",),
            },
        ),
    ]
